status /tmp/openvpn-ExitA-status.log
dev vpn-ExitA
cert /etc/openvpn/ExitA.cert
key /etc/openvpn/ExitA.key
server 172.16.12.0 255.255.255.224 # 172.16.12.0/27 - 1-31
client-config-dir ExitA-ccd
# Above here to change per Exit config The next 2 lines are the Sites that connect
route 192.168.12.0 255.255.255.224 # Matches SiteA
route 192.168.13.0 255.255.255.224 # Matches SiteB
port 1195
proto tcp
dev-type tun
ca /etc/openvpn/ca.cert.pem
dh /etc/openvpn/dh2048.pem
tls-auth /etc/openvpn/ta.key 0 # This file is secret
keepalive 10 120
cipher DES-EDE3-CBC  # Triple-DES
comp-lzo
max-clients 20
user nobody
group nogroup
persist-key
persist-tun
verb 2
mute 10
