remote exita.vpn.example.com
status /tmp/openvpn-ExitA-status.log
dev vpn-ExitA
up /etc/openvpn/client/ExitA.up
# Above here to change per Exit config
# Next 2 lines to change per site
cert /etc/openvpn/Site01.cert
key /etc/openvpn/Site01.key
client
port 1195
proto tcp
dev-type tun
ca /etc/openvpn/ca.cert.pem
dh /etc/openvpn/dh2048.pem
tls-auth /etc/openvpn/ta.key 1 # This file is secret
remote-cert-tls server
tls-version-min 1.0
keepalive 10 120
#;cipher BF-CBC        # Blowfish (default)
#;cipher AES-128-CBC   # AES
cipher DES-EDE3-CBC  # Triple-DES
comp-lzo
max-clients 10
user nobody
group proxy
persist-key
persist-tun
verb 2
mute 10
script-security 2

